// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXo_kRoQYtzr3mffTUFWr2h1kT0uS4XCM',
    appId: '1:150930906470:web:bf77a2e709a320f7aa3ca7',
    messagingSenderId: '150930906470',
    projectId: 'zenith-habits',
    authDomain: 'zenith-habits.firebaseapp.com',
    storageBucket: 'zenith-habits.appspot.com',
    measurementId: 'G-757C7PB6F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSqK_vPSCsRctCe0pCyPCj3aeCvhtwqs',
    appId: '1:150930906470:android:0af7df01caa48ac5aa3ca7',
    messagingSenderId: '150930906470',
    projectId: 'zenith-habits',
    storageBucket: 'zenith-habits.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5JU3honFu0JNBxxko3jgNBneL-_ojNUI',
    appId: '1:150930906470:ios:056d8bade0390a73aa3ca7',
    messagingSenderId: '150930906470',
    projectId: 'zenith-habits',
    storageBucket: 'zenith-habits.appspot.com',
    iosBundleId: 'com.example.zenithhabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5JU3honFu0JNBxxko3jgNBneL-_ojNUI',
    appId: '1:150930906470:ios:cb2c3725ec9d4a8eaa3ca7',
    messagingSenderId: '150930906470',
    projectId: 'zenith-habits',
    storageBucket: 'zenith-habits.appspot.com',
    iosBundleId: 'com.example.zenithhabits.RunnerTests',
  );
}
